### ISSUE TITLE
Make demonstration notebook for text to image

### ISSUE THREAD

**Issue by haltingstate** [kk-digital/kcg-ml-sd1p4#8]
https://github.com/kk-digital/kcg-ml-sd1p4/blob/main/stable_diffusion/scripts/text_to_image.py

---

Make a demo notebook
- takes in a text prompt
- outputs an image

Show each of the steps individually and today

---

# Get the prompt embeddings
            cond = self.model.get_text_conditioning(prompts)

---

x = self.sampler.sample(cond=cond,
                                    shape=[batch_size, c, h // f, w // f],
                                    uncond_scale=uncond_scale,
                                    uncond_cond=un_cond)

---

# Decode the image from the [autoencoder](../model/autoencoder.html)
            images = self.model.autoencoder_decode(x)

---

# Save images
        save_images(images, dest_path, 'txt_')

**Comment by ASAD-BE18** [comment]
Added the demonstration notebook
